import { Domain, TldInfo, GeneratedDomain, Industry, SaleDomainResult, SaleCategory, CountryCode, Translation, SaleDomain } from './modals/api-types';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class ApiService {
  truelink = 'http://www.anrdoezrs.net/links/9133603/type/dlg/' +
    'https://godaddy.com/whois/results.aspx?isc=cjc99com&checkAvail=1&tmskey=&domain=';
  falselink = 'http://www.anrdoezrs.net/links/9133603/type/dlg' +
    '/https://godaddy.com/domainsearch/find?isc=cjc99com&checkAvail=1&tmskey=&domainToCheck=';
  tldList: TldInfo[] = [];
  allTldList: TldInfo[] = [];
  tldCats: string[] = [];
  initSaleDomains: SaleDomain[] = [];
  industries: Industry[] = [];
  saleCategories: SaleCategory[] = [];
  countryCode: CountryCode = {
    country: '',
  };
  keyword = '';
  translations: Translation[] = [{
    lang: 'English',
    code: 'en',
    data: {
      url: '/en/',
      just_start_typing: 'Just start typing...',
      extension_url: 'extensions',
      generator_url: 'generator',
      sale_url: 'sale',
      native_name: 'English',
      h1: 'Instant Domain Name Search',
      primium_h2: 'Premium Names ',
      serious_about_h3: 'Serious about your business name? Get a premium business name from Domainify branding experts. Logo, domain and transfer within 24 hours included.',
      all: 'All',
      extension: 'Extensions',
      generator: 'Generator',
      for_sale: 'For Sale',
      view_more: 'View More',
      see_all: 'See All',
      buy: 'Buy',
      expired: 'Expired',
      visit_site: 'Visit Site',
      appraise: 'Appraise',
      google_search: 'Google Search',
      wayback_machine: 'WayBack Machine',
      choose_your_language: 'Choose your language',
      category: 'Category',
      min: 'Min',
      max: 'Max',
      apply: 'Apply',
      select_filter: 'Select a filter',
      popular: 'Popular',
      featured: 'Featured',
      select_an_industry: 'Select an industry for more accurate results',
      industry_filter: 'Industry Filter',
      character: 'Characters'
    }
  },
  {
    lang: 'Arabic',
    code: 'ar',
    data: {
      url: '/ar/',
      just_start_typing: 'البدء بالكتابة',
      extension_url: 'extensions',
      generator_url: 'generator',
      sale_url: 'sale',
      native_name: 'العربية',
      h1: ' موقع للبحث الفوري عن أسماء المجالات ',
      primium_h2: 'مواقع ذات فعالية عالية',
      serious_about_h3: 'هل انت راض عن العلامة التجارية؟ احصل الآن على اسم تجاري من موقع Domainify و شعار للعلامة التجارية  واسم نطاق في غضون 24 ساعة فقط',
      all: ' الكل',
      extension: 'الإضافات',
      generator: 'اقتراح اسم مجال',
      for_sale: 'للبيع',
      view_more: 'مشاهدة المزيد من النتئج',
      see_all: 'مشاهدة جميع النتائج',
      buy: 'شراء',
      expired: 'نطاق منتهي الصلاحية',
      visit_site: 'قم بزيارة الموقع',
      appraise: 'لتقييم سعر المجال ',
      google_search: 'البحث في محرك جوجل',
      wayback_machine: 'الأرشيف الرقمي المتجدد ',
      choose_your_language: 'اختر اللغة المناسبة',
      category: 'الفئة',
      min: 'الحد الأدنى ',
      max: 'الحد الأقصى',
      apply: 'تطبيق',
      select_filter: 'ترشيح النتائج',
      popular: 'أكثر شعبية',
      featured: 'متميز',
      select_an_industry: 'اختيار مهنة لنتائج أكثر دقة',
      industry_filter: 'تصفية النتائج حسب المهنة ',
      character: 'الشخصيات'
    }
  },
  {
    lang: 'Bengali',
    code: 'bn',
    data: {
      url: '/bn/',
      just_start_typing: 'এক্ষুনি টাইপ শুরু করুন',
      extension_url: 'extensions',
      generator_url: 'generator',
      sale_url: 'sale',
      native_name: 'বাংলা',
      h1: 'তাৎক্ষনিকভাবে ডোমেইন নাম অনুসন্ধান',
      primium_h2: 'প্রিমিয়াম নামসমূহ',
      serious_about_h3: 'আপনার ব্যবসায়ের নাম নির্ধারণের ব্যাপারে চিন্তা করছেন? Domainify এর ব্র্যান্ডিং বিশেষজ্ঞদের থেকে একটি প্রিমিয়াম ব্যবসায়িক নাম নিন। লোগো, ডোমেন এবং স্থানান্তর ২৪ ঘণ্টার মধ্যে সম্পন্ন করা হয়।',
      all: 'সব',
      extension: 'এক্সটেনশনসমূহ',
      generator: 'উদ্ভাবক',
      for_sale: 'বিক্রয় হবে',
      view_more: 'আরো দেখুন',
      see_all: 'সবগুলি দেখুন',
      buy: 'ক্রয় করুন',
      expired: 'মেয়াদ শেষ',
      visit_site: 'ওয়েবসাইট ভিজিট করুন',
      appraise: 'মূল্যায়ন করুন',
      google_search: 'Google অনুসন্ধান',
      wayback_machine: 'WayBack মেশিন',
      choose_your_language: 'আপনার ভাষা নির্বাচন করুন',
      category: 'বিভাগ',
      min: 'সর্বনিম্ন',
      max: 'সর্বোচ্চ',
      apply: 'প্রয়োগ করুন',
      select_filter: 'একটি ফিল্টার নির্বাচন করুন',
      popular: 'জনপ্রিয়',
      featured: 'বৈশিষ্ট্যযুক্ত',
      select_an_industry: 'আরও সঠিক ফলাফলের জন্য একটি ইন্ডাস্ট্রি নির্বাচন করুন',
      industry_filter: 'ইন্ডাস্ট্রি ফিল্টার',
      character: 'বর্ণ'
    }
  },
  {
    lang: 'Croatian',
    code: 'hr',
    data: {
      url: '/hr/',
      just_start_typing: 'Samo počnite tipkati...',
      extension_url: 'prosirenja',
      generator_url: 'generator',
      sale_url: 'na-prodaju',
      native_name: 'Hrvatski jezik',
      h1: 'Trenutno pretraživanje imena domene',
      primium_h2: 'Premium imena',
      serious_about_h3: 'Ozbiljni ste u vezi s imenom svoje tvrtke? Nabavite vrhunsko poslovno ime od stručnjaka za brendiranje s Domainify. Uključeni su logotip, domena i prijenos u roku od 24 sata.',
      all: 'Sve',
      extension: 'Proširenja',
      generator: 'Generator',
      for_sale: 'Na prodaju',
      view_more: 'Pogledajte više',
      see_all: 'Pogledajte sve',
      buy: 'Kupite',
      expired: 'Isteklo',
      visit_site: 'Posjetite stranicu',
      appraise: 'Procjena',
      google_search: 'Pretraživanje na Googleu',
      wayback_machine: 'WayBack Machine',
      choose_your_language: 'Odaberite svoj jezik',
      category: 'Kategorija',
      min: 'Min.',
      max: 'Maks.',
      apply: 'Primijeni',
      select_filter: 'Odaberite filtar',
      popular: 'Popularno',
      featured: 'Istaknuto',
      select_an_industry: 'Odaberite industriju za preciznije rezultate',
      industry_filter: 'Filtar za industriju',
      character: 'Znakovi'
    }
  },
  {
    lang: 'Czech',
    code: 'cs',
    data: {
      url: '/cs/',
      just_start_typing: 'Začněte psát ...',
      extension_url: 'pripony',
      generator_url: 'generator',
      sale_url: 'na-prodej',
      native_name: 'Čeština',
      h1: 'Okamžité vyhledávání názvů domén',
      primium_h2: 'Prémiové jména',
      serious_about_h3: 'Myslíte to s vaším obchodním jménem vážně? Získejte prémiové obchodní jméno od odborníků na značky z Domainify. Zahrnuté je i logo, doména a převod do 24 hodin.',
      all: 'Všechno',
      extension: 'Přípony',
      generator: 'Generátor',
      for_sale: 'Na prodej',
      view_more: 'Zobrazit více',
      see_all: 'Zobrazit vše',
      buy: 'Koupit',
      expired: 'Platnost vypršela',
      visit_site: 'Navštívit stránku',
      appraise: 'Ohodnotit',
      google_search: 'Google vyhledávání',
      wayback_machine: 'WayBack Machine',
      choose_your_language: 'Zvolte si jazyk',
      category: 'Kategorie',
      min: 'Min',
      max: 'Max',
      apply: 'Použít',
      select_filter: 'Zvolte si filtr',
      popular: 'Oblíbené',
      featured: 'Navrhované',
      select_an_industry: 'Pro přesnější výsledky si zvolte odvětví',
      industry_filter: 'Filtr odvětví',
      character: 'Znaky'
    }
  },
  {
    lang: 'Dutch',
    code: 'nl',
    data: {
      url: '/nl/',
      just_start_typing: 'Start met typen...',
      extension_url: 'uitbreidingen',
      generator_url: 'generator',
      sale_url: 'te-koop',
      native_name: 'Nederlands',
      h1: 'Directe zoekopdracht naar domeinnamen',
      primium_h2: 'Premiumnamen',
      serious_about_h3: 'U neemt uw bedrijfsnaam serieus? Ontvang een premium bedrijfsnaam van onze Domainify-deskundigen. Logo, domein en transfer binnen 24 uur zijn inbegrepen.',
      all: 'Alles',
      extension: 'Uitbreidingen',
      generator: 'Generator',
      for_sale: 'Te koop',
      view_more: 'Bekijk meer',
      see_all: 'Bekijk alles',
      buy: 'Koop',
      expired: 'Verlopen',
      visit_site: 'Bezoek site',
      appraise: 'Beoordeling',
      google_search: 'Google Zoeken',
      wayback_machine: 'WayBack Machine',
      choose_your_language: 'Kies uw taal',
      category: 'Categorie',
      min: 'Min',
      max: 'Max',
      apply: 'Toepassen',
      select_filter: 'Selecteer een filter',
      popular: 'Populair',
      featured: 'In de kijker',
      select_an_industry: 'Selecteer een sector voor nauwkeurigere resultaten',
      industry_filter: 'Filter sector',
      character: 'Karakters'
    }
  },
  {
    lang: 'Finnish',
    code: 'fi',
    data: {
      url: '/fi/',
      just_start_typing: 'Aloita vain kirjoittaminen...',
      extension_url: 'ylatason-verkkotunnukset',
      generator_url: 'generointi',
      sale_url: 'myynnissa',
      native_name: 'Suomi',
      h1: 'Hae verkkotunnusta suoraan',
      primium_h2: 'Korkealuokkaiset nimet',
      serious_about_h3: 'Oletko tosissaan sinun yrityksen nimestäsi? Saa korkealuokkainen yritysnimike Domainify brändäys ammattilaisilta. Tähän sisältyy logo, verkkotunnus ja sen siirto 24 tunnin kuluessa.',
      all: 'Kaikki',
      extension: 'Ylätason verkkotunnukset',
      generator: 'Generointi',
      for_sale: 'Myynnissä',
      view_more: 'Näe lisää',
      see_all: 'Näe kaikki',
      buy: 'Osta',
      expired: 'Erääntynyt',
      visit_site: 'Käy sivustolla',
      appraise: 'Arvostele',
      google_search: 'Google Haku',
      wayback_machine: 'WayBack Machine',
      choose_your_language: 'Valitse kielesi',
      category: 'Ryhmä',
      min: 'Minimi',
      max: 'Maksimi',
      apply: 'Hakea',
      select_filter: 'Valitse suodatin',
      popular: 'Suosittu',
      featured: 'Mainostettu',
      select_an_industry: 'Valitse toimiala tarkempia tuloksia varten',
      industry_filter: 'Toimiala Suodatin',
      character: 'Merkit'
    }
  },
  {
    lang: 'French',
    code: 'fr',
    data: {
      url: '/fr/',
      just_start_typing: 'Commercer à écrire...',
      extension_url: 'extensions',
      generator_url: 'generateur',
      sale_url: 'en-vente',
      native_name: 'Français',
      h1: 'Recherche instantanée de noms de domaine',
      primium_h2: 'Noms Premiums',
      serious_about_h3: 'Sérieux sur le nom de votre entreprise? Obtenez un nom commercial de qualité grâce aux experts en stratégie de marque de Domainify. Le logo, le domaine et le transfert sont inclus sous 24 heures.',
      all: 'Tout',
      extension: 'Extensions',
      generator: 'Générateur',
      for_sale: 'En vente',
      view_more: 'Voir davantage',
      see_all: 'Tout voir',
      buy: 'Acheter',
      expired: 'Expiré',
      visit_site: 'Aller sur le site',
      appraise: 'Estimer',
      google_search: 'Recherche Google',
      wayback_machine: 'WayBack Machine',
      choose_your_language: 'Choissisez votre langue',
      category: 'Catégorie',
      min: 'Min',
      max: 'Max',
      apply: 'Appliquer',
      select_filter: 'Choississez un filtre',
      popular: 'Populaire',
      featured: 'Mis en avant',
      select_an_industry: 'Sélectionnez une industrie pour un résultat plus précis',
      industry_filter: 'FIltre par Industrie',
      character: 'Caractères'
    }
  },
  {
    lang: 'German',
    code: 'de',
    data: {
      url: '/de/',
      just_start_typing: 'Einfach eingeben...',
      extension_url: 'endungen',
      generator_url: 'generator',
      sale_url: 'zun-verkauf',
      native_name: 'Deutsch',
      h1: 'Sofortige Domainnamen-Suche',
      primium_h2: 'Premium Namen',
      serious_about_h3: 'Ihnen ist Ihr Geschäftsname wichtig? Holen Sie sich einen Premium Business Namen von den Domainify Experten. Logo, Domain und Transfer innerhalb von 24 Stunden inklusive.',
      all: 'Alle',
      extension: 'Endungen',
      generator: 'Generator',
      for_sale: 'Mehr ansehen',
      view_more: 'Zun Verkauf',
      see_all: 'Alle ansehen',
      buy: 'Kaufen',
      expired: 'Abgelaufen',
      visit_site: 'Seite besuchen',
      appraise: 'Bewerten',
      google_search: 'Google Suche',
      wayback_machine: 'WayBack Maschine',
      choose_your_language: 'Sprache auswählen',
      category: 'Kategorie',
      min: 'Min',
      max: 'Max',
      apply: 'Anwenden',
      select_filter: 'Filter auswählen',
      popular: 'Beliebt',
      featured: 'Beworben',
      select_an_industry: 'Wählen Sie eine Branche für genauere Ergebnisse aus',
      industry_filter: 'Branchenfilter',
      character: 'Zeichen'
    }
  },
  {
    lang: 'Greek',
    code: 'el',
    data: {
      url: '/el/',
      just_start_typing: 'Πληκτρολογήστε...',
      extension_url: 'extensions',
      generator_url: 'generator',
      sale_url: 'sale',
      native_name: 'Eλληνικά',
      h1: 'Αμεση αναζήτηση για όνομα domain',
      primium_h2: 'Premium Ονόματα',
      serious_about_h3: 'Παίρνετε στα σοβαρά το όνομα της επιχείρησής σας; Αποκτήστε ένα premium όνομα επιχείρησης από τους ειδικούς μαρκετίστες του Domainify. Περιλαμβάνεται λογότυπο, domain και μεταφορά εντός 24 ωρών.',
      all: 'Όλα',
      extension: 'Επεκτάσεις',
      generator: 'Δημιουργία',
      for_sale: 'Προς πώληση',
      view_more: 'Προς πώληση',
      see_all: 'Όλα',
      buy: 'Αγοράστε',
      expired: 'Έληξε',
      visit_site: 'Επίσκεψη ',
      appraise: 'Αξιολόγηση',
      google_search: 'Αναζήτηση Google',
      wayback_machine: 'Μηχανή WayBack',
      choose_your_language: 'Επιλέξτε τη γλώσσα σας',
      category: 'Κατηγορία',
      min: 'Ελάχ.',
      max: 'Μέγ.',
      apply: 'Εφαρμογή',
      select_filter: 'Επιλογή φίλτρου',
      popular: 'Δημοφιλή',
      featured: 'Προτεινόμενα',
      select_an_industry: 'Επιλέξτε μια βιομηχανία για ακριβέστερα αποτελέσματα',
      industry_filter: 'Φίλτρο Βιομηχανίας',
      character: 'Χαρακτήρες'
    }
  },
  {
    lang: 'Hindi',
    code: 'hi',
    data: {
      url: '/hi/',
      just_start_typing: 'बस टाइप करना शुरू करें...',
      extension_url: 'extensions',
      generator_url: 'generator',
      sale_url: 'sale',
      native_name: 'हिन्दी',
      h1: 'डोमेन नाम की त्वरित खोज',
      primium_h2: 'प्रीमियम नाम',
      serious_about_h3: 'अपने व्यवसाय के नाम के बारे में गंभीर हैं? Domainify ब्रांडिंग विशेषज्ञों से एक प्रीमियम व्यवसाय नाम प्राप्त करें। 24 घंटे के भीतर लोगो, डोमेन और स्थानांतरण शामिल हैं।',
      all: 'सभी',
      extension: 'एक्सटेंशन्स',
      generator: 'जनरेटर',
      for_sale: 'बिक्री के लिए',
      view_more: 'और देखिये',
      see_all: 'सभी देखिये',
      buy: 'खरीदें',
      expired: 'समय सीमा समाप्त',
      visit_site: 'साइट पर जाएं',
      appraise: 'मूल्यांकन करें',
      google_search: 'Google खोज ',
      wayback_machine: 'WayBack Machine',
      choose_your_language: 'अपनी भाषा चुनिये',
      category: 'श्रेणी',
      min: 'न्यूनतम',
      max: 'अधिकतम',
      apply: 'लागू करो',
      select_filter: 'एक फिल्टर चुनिये',
      popular: 'लोकप्रिय',
      featured: 'फीचर्ड',
      select_an_industry: 'अधिक सटीक परिणामों के लिए एक उद्योग का चयन करें',
      industry_filter: 'उद्योग फिल्टर ',
      character: 'अक्षर'
    }
  },
  {
    lang: 'Hungarian',
    code: 'hu',
    data: {
      url: '/hu/',
      just_start_typing: 'Kezdje el beírni...',
      extension_url: 'kiterjesztesek',
      generator_url: 'generator',
      sale_url: 'elado',
      native_name: 'Magyar',
      h1: 'Domainnév azonnali keresése ',
      primium_h2: 'Prémium nevek',
      serious_about_h3: 'Fontos Önnek a vállalkozása neve? Legyen az Öné egy kiváló cégnév a Domainify márkaépítési szakértői jóvoltából! A szolgáltatás tartalmazza a logót, a domaint és a 24 órán belüli transzfert.',
      all: 'Minden',
      extension: 'Kiterjesztések',
      generator: 'Generátor',
      for_sale: 'Eladó',
      view_more: 'Megnézek többet',
      see_all: 'Megnézem mindet',
      buy: 'Megveszem',
      expired: 'Lejárt',
      visit_site: 'Meglátogatom az oldalt',
      appraise: 'Értékbecslés',
      google_search: 'Google kereső',
      wayback_machine: 'WayBack Machine',
      choose_your_language: 'Válasszon nyelvet!',
      category: 'Kategória',
      min: 'Min.',
      max: 'Max.',
      apply: 'Alkalmaz',
      select_filter: 'Válasszon szűrőt!',
      popular: 'Népszerű',
      featured: 'Kiemelt',
      select_an_industry: 'A pontosabb találatokhoz válasszon ki egy iparágat!',
      industry_filter: 'Iparág szerinti szűrő',
      character: 'Betűhelyek'
    }
  },
  {
    lang: 'Indonesian',
    code: 'id',
    data: {
      url: '/id/',
      just_start_typing: 'Tinggal ketik saja...',
      extension_url: 'ekstensi',
      generator_url: 'generator',
      sale_url: 'dijual',
      native_name: 'Bahasa',
      h1: 'Pencarian Nama Domain Secara Instan',
      primium_h2: 'Nama Premium',
      serious_about_h3: 'Serius dengan nama bisnis Anda? Dapatkan nama bisnis premium dari para ahli branding Domainify. Logo, domain dan transfer diselesaikan dalam waktu 24 jam.',
      all: 'Semuanya',
      extension: 'Ekstensi',
      generator: 'Generator',
      for_sale: 'Dijual',
      view_more: 'Lihat Lainnya',
      see_all: 'Lihat Semua',
      buy: 'Beli',
      expired: 'Kedaluwarsa',
      visit_site: 'Kunjungi Situs',
      appraise: 'Beri Nilai',
      google_search: 'Pencarian Google',
      wayback_machine: 'WayBack Machine',
      choose_your_language: 'Pilih bahasa',
      category: 'Kategori',
      min: 'Min',
      max: 'Maks',
      apply: 'Terapkan',
      select_filter: 'Pilih filter',
      popular: 'Populer',
      featured: 'Unggulan',
      select_an_industry: 'Pilih industri untuk mendapatkan hasil yang lebih akurat',
      industry_filter: 'Filter Industri',
      character: 'Karakter'
    }
  },
  {
    lang: 'Italian',
    code: 'it',
    data: {
      url: '/it/',
      just_start_typing: 'Inizia semplicemente a digitare...',
      extension_url: 'estensioni',
      generator_url: 'generatore',
      sale_url: 'in-vendita',
      native_name: 'Italiano',
      h1: 'Ricerca Instantanea di Dominio',
      primium_h2: 'Nomi Premium',
      serious_about_h3: 'Vuoi trovare un nome per il tuo business? Ottieni un nome premium per la tua azienda dagli esperti di branding di Domainify. Inclusi logo, dominio e trasferimento entro 24 ore.',
      all: 'Tutto',
      extension: 'Estensioni',
      generator: 'Generatore',
      for_sale: 'In Vendita',
      view_more: 'Scopri di più',
      see_all: 'Vedi tutto',
      buy: 'Compra',
      expired: 'Scaduto',
      visit_site: 'Visita il Sito',
      appraise: 'Valuta ',
      google_search: 'Ricerca Google',
      wayback_machine: 'WayBack Machine',
      choose_your_language: 'Scegli la tua lingua',
      category: 'Categoria',
      min: 'Min',
      max: 'Max',
      apply: 'Applica ',
      select_filter: 'Scegli un filtro',
      popular: 'Popolare',
      featured: 'In primo piano',
      select_an_industry: 'Scegli un\'industria per risultati più accurati',
      industry_filter: 'Filtro Industria',
      character: 'Caratteri'
    }
  },
  {
    lang: 'Japanese',
    code: 'ja',
    data: {
      url: '/ja/',
      just_start_typing: 'こちらでご入力...',
      extension_url: 'extensions',
      generator_url: 'generator',
      sale_url: 'sale',
      native_name: '日本語',
      h1: '即座ドメイン名検索',
      primium_h2: 'プレミアムドメイン名',
      serious_about_h3: 'お客様のビジネス名をご検討中ですか？Domainifyのブランディング専門家よりプレミアムなビジネス名がご入手できます。ロゴ、ドメイン、お客様のデータ転送は全部含めて24時間内に終了可能です。',
      all: '検索結果すべて見る',
      extension: 'ドメイン名エクステンション',
      generator: 'ドメイン名ジェネレータ',
      for_sale: '現在販売中',
      view_more: 'もっと見る',
      see_all: '検索結果全て見る',
      buy: '購入',
      expired: '期限切れ',
      visit_site: 'ご覧になっているウエブサイトを開く',
      appraise: '値踏み',
      google_search: 'グーグル検索',
      wayback_machine: 'WayBackマシーン',
      choose_your_language: '言語を選択',
      category: 'カテゴリー',
      min: '極小値',
      max: '極大値',
      apply: '設定を適用',
      select_filter: 'フィルターを選択',
      popular: '人気ドメイン名',
      featured: '注目ドメイン名',
      select_an_industry: '業界を選択してより適切な検索結果を',
      industry_filter: '業界別フィルター',
      character: 'ご入力文字数'
    }
  },
  {
    lang: 'Korean',
    code: 'ko',
    data: {
      url: '/ko/',
      just_start_typing: '여기에 입력하세요...',
      extension_url: 'extensions',
      generator_url: 'generator',
      sale_url: 'sale',
      native_name: '한국어',
      h1: '도메인명 빠른 검색',
      primium_h2: '프리미엄 도메인명',
      serious_about_h3: '고객님의 비즈니스명을 고려 중이신가요? Domainify의 브랜딩 전문가로부터 프리미엄명을 입수할 수 있습니다. 로고, 도메인 및 변경을 모두 포함하여 24시간 내에 완료됩니다.',
      all: '전체',
      extension: '확장',
      generator: '생성기',
      for_sale: '판매 중',
      view_more: '더 보기',
      see_all: '전체 보기',
      buy: '구입',
      expired: '만료',
      visit_site: '웹사이트 방문',
      appraise: '평가',
      google_search: '구글 검색',
      wayback_machine: '웨이백 머신 (Wayback Machine)',
      choose_your_language: '언어 선택하기',
      category: '카테고리',
      min: '최소값',
      max: '최대값',
      apply: '적용',
      select_filter: '필터 선택하기',
      popular: '인기',
      featured: '추천',
      select_an_industry: '더 정확한 결과를 위해 업계 선택하기',
      industry_filter: '업계별 필터',
      character: '문자 수'
    }
  },
  {
    lang: 'Mandarin(Chinese)',
    code: 'zh',
    data: {
      url: '/zh/',
      just_start_typing: '请开始输入',
      extension_url: 'extensions',
      generator_url: 'generator',
      sale_url: 'sale',
      native_name: '中文',
      h1: '快速查阅域名',
      primium_h2: '白金域名 ',
      serious_about_h3: '您在认真选择您的企业名字？您可以从Domainify品牌打造专家选择一个高档的企业名字。商标，域名以及在二十四小时之内转入程序都包含在内。',
      all: '所有',
      extension: '域名后缀',
      generator: '生成器',
      for_sale: '购买域名',
      view_more: '查阅更多内容',
      see_all: '查看所有',
      buy: '购买',
      expired: '过期',
      visit_site: '游览此网址',
      appraise: '评估价格',
      google_search: '谷歌搜寻',
      wayback_machine: '网站时光机',
      choose_your_language: '选择你的语言',
      category: '类别',
      min: '最低',
      max: '最高',
      apply: '登记',
      select_filter: '选择一个筛选条件',
      popular: '受欢迎',
      featured: '精选',
      select_an_industry: '选择一种行业以获得更准确的结果',
      industry_filter: '行业筛选',
      character: '字符'
    }
  },
  {
    lang: 'Marathi',
    code: 'mr',
    data: {
      url: '/mr/',
      just_start_typing: 'फक्त टाईप करायला सुरवात करा ',
      extension_url: 'extensions',
      generator_url: 'generator',
      sale_url: 'sale',
      native_name: 'मराठी',
      h1: 'डोमेन नावाचा जलद शोध',
      primium_h2: 'प्रीमियम नाव ',
      serious_about_h3: 'आपल्या व्यवसायाच्या नावासाठी चिंतीत आहात? डोमेनफाय ब्रँडिंग तज्ञांकडून एक प्रीमियम व्यावसाईक नाव प्राप्त करा. लोगो, डोमेन आणि हस्तांतरण २४ तासांच्या आत.',
      all: 'सर्व ',
      extension: 'एक्सटेन्शन्स ',
      generator: 'जनरेटर',
      for_sale: 'विक्रीसाठी ',
      view_more: 'आणखी पाहा ',
      see_all: 'सर्व बघा ',
      buy: 'खरेदी करा ',
      expired: 'वेळ मर्यादा समाप्त ',
      visit_site: 'साईट वर जा ',
      appraise: 'मूल्य काढा ',
      google_search: 'Google शोध',
      wayback_machine: 'WayBack Machine',
      choose_your_language: 'आपली भाषा निवडा ',
      category: 'श्रेणी',
      min: 'किमान',
      max: 'कमाल',
      apply: 'लागू करा',
      select_filter: 'एक फिल्टर nivda',
      popular: 'लोकप्रिय',
      featured: 'फीचर्ड',
      select_an_industry: 'आणखी अचूक परिणामांसाठी एका उद्योगाची निवड करा',
      industry_filter: 'उद्योग फिल्टर',
      character: 'अक्षर'
    }
  },
  {
    lang: 'Norwegian',
    code: 'no',
    data: {
      url: '/no/',
      just_start_typing: 'Bare begynn å skrive ...',
      extension_url: 'forlengelse',
      generator_url: 'generator',
      sale_url: 'til-salgs',
      native_name: 'Norsk',
      h1: 'Direkte søk etter domenenavn',
      primium_h2: 'Premium-navn',
      serious_about_h3: 'Er du seriøs med navnet på bedriften din ? Få et premium forretningsnavn fra Domainify merkevareeksperter. Logo, domene og overføring innen 24 timer inkludert.',
      all: 'Alt',
      extension: 'Forlengelse',
      generator: 'Generator',
      for_sale: 'Til salgs',
      view_more: 'Se mer',
      see_all: 'Se alt',
      buy: 'Kjøp',
      expired: 'Utløpt',
      visit_site: 'Besøk nettstedet',
      appraise: 'Vurdere',
      google_search: 'Google-søk',
      wayback_machine: 'WayBack Machine',
      choose_your_language: 'Velg språket ditt',
      category: 'Kategori',
      min: 'Min.',
      max: 'Maks.',
      apply: 'Bruke',
      select_filter: 'Valg et filter',
      popular: 'Populær',
      featured: 'Omtalt',
      select_an_industry: 'Velg en bransje for mer nøyaktige resultater',
      industry_filter: 'Bransjefilter',
      character: 'Karakterer'
    }
  },
  {
    lang: 'Polish',
    code: 'pl',
    data: {
      url: '/pl/',
      just_start_typing: 'Zacznij pisać ',
      extension_url: 'rozszerzenia',
      generator_url: 'wygeneruj',
      sale_url: 'na-sprzedaz',
      native_name: 'Język polski',
      h1: 'Natychmiastowe wyszukiwanie nazw domen',
      primium_h2: 'Nazwy o najwyższej wyszukiwalności',
      serious_about_h3: 'Na poważnie traktujesz nazwę swojej firmy? Odbierz nazwę o najwyższej wyszukiwalności od ekspertów branży z Domainify. Logo, domena i przekaz wszystko to w 24 godziny. ',
      all: 'Wszystkie ',
      extension: 'Rozszerzenia ',
      generator: 'Wygeneruj',
      for_sale: 'Na sprzedaż',
      view_more: 'Zobacz Więcej',
      see_all: 'Zobacz Wszystko ',
      buy: 'Kupuj ',
      expired: 'Wygasła',
      visit_site: 'Odwiedź Stronę',
      appraise: 'Oszacuj',
      google_search: 'Przeszykiwanie Google',
      wayback_machine: 'Wróć na stronę korzystając z WayBack Machine',
      choose_your_language: 'Wybierz swój język',
      category: 'Kategoria',
      min: 'Minimum',
      max: 'Maksymum',
      apply: 'Zastosuj',
      select_filter: 'Wybierz filtr',
      popular: 'Popularne',
      featured: 'Wyróżnione',
      select_an_industry: 'Wybierz branżę aby otrzymać dokładniejszy rezultat',
      industry_filter: 'Filtr branży',
      character: 'Znaki'
    }
  },
  {
    lang: 'Portuguese',
    code: 'pt',
    data: {
      url: '/pt/',
      just_start_typing: 'Só começando a digitar...',
      extension_url: 'extensoes',
      generator_url: 'gerador',
      sale_url: 'disponivel',
      native_name: 'Português',
      h1: 'Pesquisa de Nomes Domínio Instantâneo',
      primium_h2: 'Nomes Premium ',
      serious_about_h3: 'Preocupado com o nome da sua empresa? Consiga um nome de empresa premium dos experts de marca Domainify. Logo, domínio e transferência dentro de 24 horas incluso.',
      all: 'Tudo ',
      extension: 'Extensões ',
      generator: 'Gerador',
      for_sale: 'Disponível ',
      view_more: 'Ver Mais',
      see_all: 'Ver Tudo',
      buy: 'Comprar',
      expired: 'Expirado',
      visit_site: 'Visitar Site',
      appraise: 'Avaliar',
      google_search: 'Pesquisa do Google',
      wayback_machine: 'WayBack Machine',
      choose_your_language: 'Escolher seu idioma',
      category: 'Categoria',
      min: 'Mín',
      max: 'Máx',
      apply: 'Solicitar',
      select_filter: 'Selecionar um filtro',
      popular: 'Popular',
      featured: 'Em destaque',
      select_an_industry: 'Seleciona um mercado para resultados mais precisos',
      industry_filter: 'Filtro de Mercado',
      character: 'Caracteres'
    }
  },
  {
    lang: 'Punjabi',
    code: 'pa',
    data: {
      url: '/pa/',
      just_start_typing: 'ਬਸ ਟਾਈਪ ਕਰਨਾ ਸ਼ੁਰੂ ਕਰੋ...',
      extension_url: 'extensions',
      generator_url: 'generator',
      sale_url: 'sale',
      native_name: 'ਪੰਜਾਬੀ',
      h1: 'ਤਤਕਾਲ ਡੋਮੇਨ ਨਾਂ ਦੀ ਖੋਜ',
      primium_h2: 'ਪ੍ਰੀਮੀਅਮ ਨਾਂ',
      serious_about_h3: 'ਕੀ ਤੁਸੀਂ ਆਪਣੇ ਕਾਰੋਬਾਰ ਦੇ ਨਾਮ ਬਾਰੇ ਗੰਭੀਰ ਹੈ? Domainify ਦੇ ਬ੍ਰਾਂਡਿੰਗ ਮਾਹਰਾਂ ਤੋਂ ਇੱਕ ਪ੍ਰੀਮੀਅਮ ਕਾਰੋਬਾਰ ਦਾ ਨਾਮ ਪ੍ਰਾਪਤ ਕਰੋ। ਲੋਗੋ, ਡੋਮੇਨ ਅਤੇ 24 ਘੰਟਿਆਂ ਵਿੱਚ ਟ੍ਰਾਂਸਫਰ ਸ਼ਾਮਲ ਹਨ।',
      all: 'ਸਾਰੇ',
      extension: 'ਐਕਸਟੈਨਸ਼ਨਸ ',
      generator: 'ਜਨਰੇਟਰ',
      for_sale: 'ਵਿਕਰੀ ਲਈ ',
      view_more: 'ਹੋਰ ਦੇਖੋ',
      see_all: 'ਸਾਰੇ ਦੇਖੋ',
      buy: 'ਖਰੀਦੋ',
      expired: 'ਮਿਆਦ ਪੁੱਗੀ',
      visit_site: 'ਸਾਈਟ \'ਤੇ ਜਾਓ',
      appraise: 'ਮੁਲਾਂਕਣ ਕਰੋ ',
      google_search: 'Google ਖੋਜ',
      wayback_machine: 'WayBack Machine',
      choose_your_language: 'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ',
      category: 'ਸ਼੍ਰੇਣੀ',
      min: 'ਨਿਉਨਤਮ ',
      max: 'ਅਧਿਕਤਮ',
      apply: 'ਲਾਗੂ ਕਰੋ',
      select_filter: 'ਇੱਕ ਫਿਲਟਰ ਚੁਣੋ',
      popular: 'ਪ੍ਰਸਿੱਧ',
      featured: 'ਫੀਚਰਡ',
      select_an_industry: 'ਹੋਰ ਸਹੀ ਨਤੀਜਿਆਂ ਲਈ ਇੱਕ ਉਦਯੋਗ ਫਿਲਟਰ ਚੁਣੋ',
      industry_filter: 'ਉਦਯੋਗ ਫਿਲਟਰ ',
      character: 'ਅੱਖਰ'
    }
  },
  {
    lang: 'Romanian',
    code: 'ro',
    data: {
      url: '/ro/',
      just_start_typing: 'Începe să tastezi',
      extension_url: 'extensie',
      generator_url: 'generator',
      sale_url: 'de-vanzare',
      native_name: 'Română',
      h1: 'Căutare instantanee nume Domeniu',
      primium_h2: 'Nume premium',
      serious_about_h3: 'Nume premium',
      all: 'Tot',
      extension: 'Extensie ',
      generator: 'Generator',
      for_sale: 'De vânzare',
      view_more: 'Vezi mai mult',
      see_all: 'Vezi tot',
      buy: 'Cumpără',
      expired: 'Expirat ',
      visit_site: 'Vizitează site ',
      appraise: 'Estimare ',
      google_search: 'Căutare Google',
      wayback_machine: 'WayBack Machine',
      choose_your_language: 'Alege limba',
      category: 'Categorie',
      min: 'Min. ',
      max: 'Max.',
      apply: 'Aplică',
      select_filter: 'Selectează un filtru',
      popular: 'Popular',
      featured: 'Recomandat',
      select_an_industry: 'Selectează o industrie pentru rezultate mai precise',
      industry_filter: 'Filtru industrie',
      character: 'Caractere '
    }
  },
  {
    lang: 'Russian',
    code: 'ru',
    data: {
      url: '/ru/',
      just_start_typing: 'Просто начните вводить имя...',
      extension_url: 'extensions',
      generator_url: 'generator',
      sale_url: 'sale',
      native_name: 'Pусский',
      h1: 'Мгновенный Поиск Доменного Имени',
      primium_h2: 'Имена премиум-класса',
      serious_about_h3: 'Серьезно относитесь к названию своего бизнеса? Получите название бизнеса премиум-класса от экспертов брендинга Domainify. Логотип, домен и передача в течении 24 часов включительно.',
      all: 'Все имена',
      extension: 'Расширения доменных имён ',
      generator: 'Генератор имён',
      for_sale: 'Имена на продажу',
      view_more: 'Смотреть дальше',
      see_all: 'Посмотреть все',
      buy: 'Купить',
      expired: 'Истекшие имена',
      visit_site: 'Перейти на сайт',
      appraise: 'Определить стоимость',
      google_search: 'Гугл Поиск ',
      wayback_machine: 'Перейти в Интернет-архив WayBack Machine',
      choose_your_language: 'Выбрать свой язык',
      category: 'Категория',
      min: 'Мин. ',
      max: 'Макс.',
      apply: 'Применить',
      select_filter: 'Выбрать фильтр',
      popular: 'Популярные ',
      featured: 'Рекомендуемые',
      select_an_industry: 'Выберите сферу деятельности, чтобы получить более точные результаты',
      industry_filter: 'Фильтр сфер деятельности',
      character: 'Символы'
    }
  },
  {
    lang: 'Slovak',
    code: 'sk',
    data: {
      url: '/sk/',
      just_start_typing: 'Začnite písať...',
      extension_url: 'pripony',
      generator_url: 'generator',
      sale_url: 'na-predaj',
      native_name: 'Slovenčina',
      h1: 'Okamžité vyhľadávanie názvov domén',
      primium_h2: 'Prémiové mená',
      serious_about_h3: 'Myslíte to s vaším obchodným menom vážne? Získajte prémiové obchodné meno od odborníkov na značky z Domainify. Zahrnuté je aj logo, doména a prevod do 24 hodín.',
      all: 'Všetko',
      extension: 'Prípony ',
      generator: 'Generátor',
      for_sale: 'Na predaj',
      view_more: 'Zobraziť viac',
      see_all: 'Zobraziť všetko',
      buy: 'Kúpiť',
      expired: 'Expirované',
      visit_site: 'Navštíviť stránku',
      appraise: 'Ohodnotiť',
      google_search: 'Google vyhľadávanie',
      wayback_machine: 'WayBack Machine',
      choose_your_language: 'Zvoľte si jazyk',
      category: 'Kategória',
      min: 'Min ',
      max: 'Max',
      apply: 'Použiť',
      select_filter: 'Zvoľte si filter',
      popular: 'Obľúbené',
      featured: 'Navrhované',
      select_an_industry: 'Pre presnejšie výsledky si zvoľte odvetvie',
      industry_filter: 'Filter odvetvia',
      character: 'Znaky'
    }
  },
  {
    lang: 'Spanish',
    code: 'es',
    data: {
      url: '/es/ ',
      just_start_typing: 'Sólo comience a escribir...',
      extension_url: 'extensiones',
      generator_url: 'generador',
      sale_url: 'a-la-venta',
      native_name: 'Español',
      h1: 'Búsqueda instántanea de nombres de dominio',
      primium_h2: 'Nombres Premium',
      serious_about_h3: '¿Toma en serio el nombre de su empresa? Obtenga un nombre de empresa premium de los expertos en posicionamiento de marca de Domainify. Logo, dominio y transferencia dentro de 24 horas incluídos. ',
      all: 'Todo',
      extension: 'Extensiones ',
      generator: 'Generador',
      for_sale: 'A la venta',
      view_more: 'Ver Más',
      see_all: 'Ver Todo',
      buy: 'Comprar',
      expired: 'Comprar',
      visit_site: 'Visitar el Sitio',
      appraise: 'Evaluar',
      google_search: 'Búsqueda de Google',
      wayback_machine: 'Máquina WayBack',
      choose_your_language: 'Elija su Idioma',
      category: 'Categoría',
      min: 'Mín ',
      max: 'Máx ',
      apply: 'Aplicar',
      select_filter: 'Seleccionar un filtro',
      popular: 'Popular',
      featured: 'Destacado',
      select_an_industry: 'Seleccione una industria para obtener resultados más precisos',
      industry_filter: 'Filtro por Industria',
      character: 'Caracteres'
    }
  },
  {
    lang: 'Swedish',
    code: 'sv',
    data: {
      url: '/sv/',
      just_start_typing: 'Börja skriva...',
      extension_url: 'forlangning',
      generator_url: 'generator',
      sale_url: 'till-forsaljning',
      native_name: 'Svenska',
      h1: 'Snabb namnsökning efter domäner',
      primium_h2: 'Premiumnamn',
      serious_about_h3: 'Är du seriös med vad ditt företag heter? Få ett premium företgsnamn från Domaninify varumärkesexperter. Logga, domän och överföring inom 24 timmar inkluderat.',
      all: 'Alla',
      extension: 'Förlängning ',
      generator: 'Generator',
      for_sale: 'Till försäljning ',
      view_more: 'Se mer',
      see_all: 'Se alla',
      buy: 'Köp',
      expired: 'Utgången',
      visit_site: 'Besök hemsida',
      appraise: 'Bedöma ',
      google_search: 'Google-sökning',
      wayback_machine: 'Wayback Machine',
      choose_your_language: 'Välj ditt språk',
      category: 'Kategori',
      min: 'Min. ',
      max: 'Max.',
      apply: 'Tillämpa',
      select_filter: 'Välj ett filter',
      popular: 'Populära',
      featured: 'Särdrag',
      select_an_industry: 'Välj en industri för mer exakta sökresultat',
      industry_filter: 'Industrifulter',
      character: 'Karaktärer'
    }
  },
  {
    lang: 'Tamil',
    code: 'ta',
    data: {
      url: '/ta/',
      just_start_typing: 'தட்டச்சு அடிக்க தொடங்கவும்',
      extension_url: 'extensions',
      generator_url: 'generator',
      sale_url: 'sale',
      native_name: 'தமிழ்',
      h1: 'உடனடியாக தளத்தின் பெயர் தேடல்',
      primium_h2: 'உயர் மதிப்புடைய பெயர்கள்',
      serious_about_h3: 'உங்கள் வியாபார பெயரின் மீது தீவிரமாக உள்ளீர்களா? ஒரு உயர் மதிப்புடைய வியாபார பெயரை டொமைனிபை பிராண்டிங் (Domainify branding) வல்லுனரிடம் இருந்து பெற்றுக்கொள்ளலாம். மேலும் 24 மணி நேரத்திற்குள் தளம், தளத்தின் சின்னம் மற்றும் பரிமாற்றங்கள் ஒழுங்கு செய்யப்படும்.',
      all: 'அனைத்தும் ',
      extension: 'நீட்டிப்புகள்',
      generator: 'தோற்றுவித்தல்',
      for_sale: 'விற்பனைக்கு ',
      view_more: 'மேலும் பார்க்க',
      see_all: 'அனைத்தையும் பார்க்க ',
      buy: 'வாங்க',
      expired: 'காலாவதியான ',
      visit_site: 'இணையதளத்தைப் பார்க்க',
      appraise: 'மதிப்பிட',
      google_search: 'கூகிளில் தேட ',
      wayback_machine: 'வேபாக் எந்திரம்',
      choose_your_language: 'உங்கள் மொழியை தேர்ந்தெடுக்கவும் ',
      category: 'வகை',
      min: 'குறைந்தபட்சம்  ',
      max: 'அதிகபட்சம்',
      apply: 'பயன்படுத்தவும் ',
      select_filter: 'ஒரு வடிகட்டியை தேர்வு செய்யவும் ',
      popular: 'பிரபலமான',
      featured: 'சிறப்பான',
      select_an_industry: 'மிகவும் துல்லியமான முடிவுகளுக்கு ஒரு துறையை தேர்ந்தெடுக்கவும் ',
      industry_filter: 'துறையின் வடிகட்டி ',
      character: 'எழுத்துக்குறிகள்'
    }
  },
  {
    lang: 'Telugu',
    code: 'te',
    data: {
      url: '/te/',
      just_start_typing: 'జస్ట్ టైప్ చేయడం ప్రారంభించండి ...',
      extension_url: 'extensions',
      generator_url: 'generator',
      sale_url: 'sale',
      native_name: 'తెలుగు',
      h1: 'తక్షణ డొమైన్ నేమ్ శోధన',
      primium_h2: 'ప్రీమియం నేమ్స్',
      serious_about_h3: 'మీ బిజినెస్ నేమ్ గురించి తీవ్రంగా ఆలోచిస్తు న్నారా? డొమైనిఫై బ్రాండింగ్ నిపుణుల నుండి ప్రీమియం బిజినెస్ నేమ్ ను పొందండి. లోగో, డొమైన్ మరియు 24 గంటలలోపు బదిలీ లతో సహా.',
      all: 'అన్ని',
      extension: 'ఎక్స్టెన్షన్లు ',
      generator: 'జనరేటర్',
      for_sale: 'అమ్మకానికి గలవి',
      view_more: 'మరిన్నిటిని చూడండి',
      see_all: 'అన్నిటిని చూడండి',
      buy: 'కొనుగోలు చేయండి',
      expired: 'గడువు తీరింది',
      visit_site: 'సైట్ ను సందర్శించండి',
      appraise: 'అంచనా వేయడం',
      google_search: 'గూగుల్ సెర్చ్',
      wayback_machine: ' WayBack Machine',
      choose_your_language: 'మీ భాషను ఎంచుకోండి',
      category: 'కేటగిరీ',
      min: 'కనిష్ట ',
      max: 'గరిష్ట',
      apply: 'వర్తిస్తాయి',
      select_filter: 'ఫిల్టర్ ను ఎంచుకోండి',
      popular: 'ప్రముఖ',
      featured: 'ఫీచర్డ్',
      select_an_industry: 'మరింత ఖచ్చితమైన ఫలితాల కోసం ఒక పరిశ్రమను ఎంచుకోండి',
      industry_filter: 'ఇండస్ట్రీ ఫిల్టర్',
      character: 'అక్షరాలు'
    }
  },
  {
    lang: 'Thai',
    code: 'th',
    data: {
      url: '/th/',
      just_start_typing: 'เพียงแค่เริ่มพิมพ์ ... ',
      extension_url: 'extensions',
      generator_url: 'generator',
      sale_url: 'sale',
      native_name: 'ไทย',
      h1: 'ค้นหาชื่อโดเมนได้ทันที',
      primium_h2: 'ชื่อพรีเมี่ยม ',
      serious_about_h3: 'คุณจริงจังเกี่ยวกับชื่อธุรกิจของคุณใช่หรือไม่? รับบริการชื่อธุรกิจแบบพรีเมี่ยมจาก Domainify ผู้เชี่ยวชาญด้านการสร้างแบรนด์  ซึ่งรวมการให้บริการทั้งส่วนโลโก้ โดเมน และการถ่ายโอนภายใน24ชั่วโมง',
      all: 'ทั้งหมด',
      extension: 'นามสกุลโดเมน ',
      generator: 'โดเมนแนะนำ',
      for_sale: 'สำหรับขาย',
      view_more: 'ดูเพิ่มเติม',
      see_all: 'ดูทั้งหมด',
      buy: 'ซื้อ',
      expired: 'หมดอายุ',
      visit_site: 'เยี่ยมชมเว็บไซต์',
      appraise: 'ประเมินราคา',
      google_search: 'การค้นหาของ Google ',
      wayback_machine: 'WayBack Machine',
      choose_your_language: 'เลือกภาษาของคุณ',
      category: 'หมวดหมู่',
      min: 'ต่ำสุด ',
      max: 'สูงสุด',
      apply: 'สมัครใช้บริการ',
      select_filter: 'เลือกตัวกรองข้อมูล',
      popular: 'ยอดนิยม',
      featured: 'ฟีเจอร์',
      select_an_industry: 'เลือกประเภทอุตสาหกรรมเพื่อผลลัพธ์ที่ถูกต้องมากขึ้น',
      industry_filter: 'ตัวกรองประเภทอุตสาหกรรม',
      character: 'ตัวอักษร'
    }
  },
  {
    lang: 'Turkish',
    code: 'tr',
    data: {
      url: '/tr/',
      just_start_typing: 'Sadece yazmaya başlayın... ',
      extension_url: 'uzantilar',
      generator_url: 'uretec',
      sale_url: 'stilik',
      native_name: 'Türkçe',
      h1: 'Hızlı Alan Adı Arama',
      primium_h2: 'Premium Adlar',
      serious_about_h3: 'İşletme adı konusunda ciddi misiniz? Domainify marka uzmanlarından premium bir işletme adı alın. Logo, etki alanı ve 24 saat içinde transfer dahil.',
      all: 'Tümü ',
      extension: 'Uzantılar ',
      generator: 'Üreteç',
      for_sale: 'Satılık ',
      view_more: 'Daha Gazla Göster',
      see_all: 'Tümünü Gör',
      buy: 'Satın Al ',
      expired: 'Süresi Bitmiş',
      visit_site: 'Siteyi Ziyaret Et',
      appraise: 'Değerlendir',
      google_search: 'Google Arama',
      wayback_machine: 'WayBack Machine',
      choose_your_language: 'Dilinizi seçin',
      category: 'Kategori',
      min: 'Min.',
      max: 'Maks.',
      apply: 'Uygula',
      select_filter: 'Bir filtre seçin',
      popular: 'En Popüler',
      featured: 'Öne Çıkanlar',
      select_an_industry: 'Daha doğru sonuçlar için bir endüstri seçin',
      industry_filter: 'Endüstri Filtresi',
      character: 'Karakter'
    }
  },
  {
    lang: 'Urdu',
    code: 'ur',
    data: {
      url: '/ur/',
      just_start_typing: '...ابھی ٹائپ کریں',
      extension_url: 'extensions',
      generator_url: 'generator',
      sale_url: 'sale',
      native_name: 'اردو',
      h1: 'ڈومین نام کی فوری تلاش',
      primium_h2: 'پریمیم نام ',
      serious_about_h3: 'کیا آپ اپنے کاروباری نام کے بارے میں سنجیدہ ہیں؟ برانڈز کے لیے ڈومینیفائی Domainify ماہرین سے پریمیم کاروباری نام حاصل کریں۔ لوگو، ڈومین اور ٹرانسفر بھی 24 گھنٹوں کے اندر اس میں شامل ہے.',
      all: 'تمام ',
      extension: 'ایکسٹینشنز ',
      generator: 'جنریٹر',
      for_sale: 'برائے فروخت ',
      view_more: 'مزید دیکھیں',
      see_all: 'تمام دیکھیں',
      buy: 'خریدیں',
      expired: 'ایکسپائرڈ',
      visit_site: 'سائٹ پر جائیں',
      appraise: 'تخمینہ لگائیں',
      google_search: 'تخمینہ لگائیں',
      wayback_machine: 'WayBack مشین',
      choose_your_language: 'اپنی زبان منتخب کریں ',
      category: 'زمرہ',
      min: 'کم سے کم',
      max: 'زائد سے زائد',
      apply: 'درخواست کریں',
      select_filter: 'فلٹر منتخب کریں',
      popular: 'معروف',
      featured: 'نمایاں',
      select_an_industry: 'مزید درست نتائج کے لیے انڈسٹری منتخب کریں',
      industry_filter: 'انڈسٹری فلٹر',
      character: 'حروف'
    }
  },
  {
    lang: 'Vietnamese',
    code: 'vi',
    data: {
      url: '/vi/',
      just_start_typing: 'Xin bắt đầu gõ chữ',
      extension_url: 'phan-mo-rong',
      generator_url: 'cong-cu-san-zuat-ten-mien',
      sale_url: 'mua-ten-mien-co-san',
      native_name: 'Tiếng Việt',
      h1: 'Tìm nhanh tên miền',
      primium_h2: 'Tên miền chất lượng cao',
      serious_about_h3: 'Muốn chọn một tên chuyên nghiệp cho doanh nghiệp của bạn? Hãy chọn một tên doanh nghiệp cao cấp từ chuyên gia xây dựng thương hiệu Domainify. Logo, tên miền và quá trình chuyển đổi hoàn thành trong vòng 24 giờ.',
      all: 'Tất cả ',
      extension: 'Phần mở rộng ',
      generator: 'Công cụ sản xuất tên miền',
      for_sale: 'Mua tên miền có sẵn ',
      view_more: 'Xem thêm',
      see_all: 'Xem tất cả',
      buy: 'Mua',
      expired: 'Quá hạn',
      visit_site: 'Ghé thăm trang web',
      appraise: 'Định giá tên miền',
      google_search: 'Tìm kiếm trên Google',
      wayback_machine: 'Kho lưu trữ Wayback Machine',
      choose_your_language: 'Chọn ngôn ngữ',
      category: 'Thể loại',
      min: 'Tối thiểu ',
      max: 'Tối đa',
      apply: 'Đăng kí',
      select_filter: 'Chọn lọc kết quả',
      popular: 'Phổ biến',
      featured: 'Nổi bật',
      select_an_industry: 'Hãy chọn một lĩnh vực kinh doanh để nhận được kết quả chính xác hơn',
      industry_filter: 'Chọn lọc kết quả dựa trên lĩnh vực kinh doanh',
      character: 'Kí tự'
    }
  }
];


  translatingVar = 'en';
  currentTranslation: Translation;

  constructor(public http: HttpClient) { }
  getTldList(limited: boolean): Observable<TldInfo[]> {
    if (limited) {
      return this.http.post<TldInfo[]>('https://instantdomains.com/api/v1/tld', { limit: 34, country: this.countryCode.country });
    }
    return this.http.post<TldInfo[]>('https://instantdomains.com/api/v1/tld', { country: this.countryCode.country });
  }

  getDomains(keyword: string, limited?: boolean): Observable<Domain[]> {
    if (limited) {
      return this.http.post<Domain[]>('https://instantdomains.com/api/v1/domains', {
        keyword,
        limit: 34,
        country: this.countryCode.country
      });
    }
    return this.http.post<Domain[]>('https://instantdomains.com/api/v1/domains', { keyword, country: this.countryCode.country });
  }

  getGenerator(keyword: string, limited?: boolean): Observable<GeneratedDomain[]> {
    if (limited) {
      return this.http.post<GeneratedDomain[]>('https://instantdomains.com/api/v1/genrate', { keyword, limit: 34 });
    }
    return this.http.post<GeneratedDomain[]>('https://instantdomains.com/api/v1/genrate', { keyword, limit: 102 });
  }

  getForSale(keyword: string, limited?: boolean): Observable<SaleDomainResult> {
    if (limited) {
      return this.http.post<SaleDomainResult>('https://instantdomains.com/api/v1/sale', { keyword, limit: 34 });
    }
    return this.http.post<SaleDomainResult>('https://instantdomains.com/api/v1/sale', { keyword, limit: 15 });
  }

  getForSaleInit(limitSearch: number): Observable<SaleDomainResult> {
    return this.http.post<SaleDomainResult>('https://instantdomains.com/api/v1/sale', { limit: limitSearch });
  }

  getComInfo(keywordSearch: string): Observable<Domain> {
    return this.http.post<Domain>('https://instantdomains.com/api/v1/com', { keyword: keywordSearch });
  }

  getTldCats(): Observable<string[]> {
    return this.http.get<string[]>('https://instantdomains.com/api/v1/categories');
  }

  getIndustries(): Observable<Industry[]> {
    return this.http.get<Industry[]>('https://instantdomains.com/api/v1/industries');
  }

  getFilteredGenerator(keyword: string, industryIds?: number[], tld?: string, char?: number): Observable<GeneratedDomain[]> {
    return this.http.post<GeneratedDomain[]>('https://instantdomains.com/api/v1/genrate', {
      keyword,
      char: char > 0 ? char : 20,
      tld: (tld && tld.length) > 0 ? tld : '.com',
      industry_ids: (industryIds && industryIds.length > 0) ? industryIds.toString() : '1'
    });
  }

  getFilterForSale(keyword: string, categories: string, min: number, max: number, lastId: number): Observable<SaleDomainResult> {
    return this.http.post<SaleDomainResult>('https://instantdomains.com/api/v1/sale', {
      keyword,
      limit: 15,
      categories,
      min,
      max,
      last_id: lastId
    });
  }

  getSaleCategories(): Observable<SaleCategory[]> {
    return this.http.get<SaleCategory[]>('https://instantdomains.com/api/v1/salecategories');
  }
  getTldId(ex: string): number {
    return this.allTldList.find(tld => tld.tld === ex).id;
  }

  getCountrycode(): Observable<CountryCode> {
    return this.http.get<CountryCode>('https://ipinfo.io/geo?token=75562443c5d748');
  }

  // getTranslations(): Observable<Translation[]> {
  //   return this.http.get<Translation[]>('assets/translations.json');
  // }

}
