import { GeneratorComponent } from './generator/generator.component';
import { ExtensionsComponent } from './extensions/extensions.component';
import { IndexComponent } from './index/index.component';
import { SaleComponent } from './sale/sale.component';
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { SitemapComponent } from './sitemap/sitemap.component';


const routes: Routes = [
  {path: '', component: IndexComponent},
  {path: 'ar/.', component: IndexComponent},
  {path: 'bn/.', component: IndexComponent},
  {path: 'hr/.', component: IndexComponent},
  {path: 'cs/.', component: IndexComponent},
  {path: 'nl/.', component: IndexComponent},
  {path: 'fi/.', component: IndexComponent},
  {path: 'fr/.', component: IndexComponent},
  {path: 'de/.', component: IndexComponent},
  {path: 'el/.', component: IndexComponent},
  {path: 'hi/.', component: IndexComponent},
  {path: 'hu/.', component: IndexComponent},
  {path: 'id/.', component: IndexComponent},
  {path: 'it/.', component: IndexComponent},
  {path: 'ja/.', component: IndexComponent},
  {path: 'ko/.', component: IndexComponent},
  {path: 'zh/.', component: IndexComponent},
  {path: 'mr/.', component: IndexComponent},
  {path: 'no/.', component: IndexComponent},
  {path: 'pl/.', component: IndexComponent},
  {path: 'pt/.', component: IndexComponent},
  {path: 'pa/.', component: IndexComponent},
  {path: 'ro/.', component: IndexComponent},
  {path: 'ru/.', component: IndexComponent},
  {path: 'sk/.', component: IndexComponent},
  {path: 'es/.', component: IndexComponent},
  {path: 'sv/.', component: IndexComponent},
  {path: 'ta/.', component: IndexComponent},
  {path: 'te/.', component: IndexComponent},
  {path: 'th/.', component: IndexComponent},
  {path: 'tr/.', component: IndexComponent},
  {path: 'ur/.', component: IndexComponent},
  {path: 'vi/.', component: IndexComponent},
  {path: 'sitemap/.', component: SitemapComponent},
  {path: 'extensions/.', component: ExtensionsComponent},
  {path: 'ar/extensions/.', component: ExtensionsComponent},
  {path: 'bn/extensions/.', component: ExtensionsComponent},
  {path: 'hr/extensions/.', component: ExtensionsComponent},
  {path: 'cs/extensions/.', component: ExtensionsComponent},
  {path: 'nl/extensions/.', component: ExtensionsComponent},
  {path: 'fi/extensions/.', component: ExtensionsComponent},
  {path: 'fr/extensions/.', component: ExtensionsComponent},
  {path: 'de/extensions/.', component: ExtensionsComponent},
  {path: 'el/extensions/.', component: ExtensionsComponent},
  {path: 'hi/extensions/.', component: ExtensionsComponent},
  {path: 'hu/extensions/.', component: ExtensionsComponent},
  {path: 'id/extensions/.', component: ExtensionsComponent},
  {path: 'it/extensions/.', component: ExtensionsComponent},
  {path: 'ja/extensions/.', component: ExtensionsComponent},
  {path: 'ko/extensions/.', component: ExtensionsComponent},
  {path: 'zh/extensions/.', component: ExtensionsComponent},
  {path: 'mr/extensions/.', component: ExtensionsComponent},
  {path: 'no/extensions/.', component: ExtensionsComponent},
  {path: 'pl/extensions/.', component: ExtensionsComponent},
  {path: 'pt/extensions/.', component: ExtensionsComponent},
  {path: 'pa/extensions/.', component: ExtensionsComponent},
  {path: 'ro/extensions/.', component: ExtensionsComponent},
  {path: 'ru/extensions/.', component: ExtensionsComponent},
  {path: 'sk/extensions/.', component: ExtensionsComponent},
  {path: 'es/extensions/.', component: ExtensionsComponent},
  {path: 'sv/extensions/.', component: ExtensionsComponent},
  {path: 'ta/extensions/.', component: ExtensionsComponent},
  {path: 'te/extensions/.', component: ExtensionsComponent},
  {path: 'th/extensions/.', component: ExtensionsComponent},
  {path: 'tr/extensions/.', component: ExtensionsComponent},
  {path: 'ur/extensions/.', component: ExtensionsComponent},
  {path: 'vi/extensions/.', component: ExtensionsComponent},
  {path: 'generator/.', component: GeneratorComponent},
  {path: 'ar/generator/.', component: GeneratorComponent},
  {path: 'bn/generator/.', component: GeneratorComponent},
  {path: 'hr/generator/.', component: GeneratorComponent},
  {path: 'cs/generator/.', component: GeneratorComponent},
  {path: 'nl/generator/.', component: GeneratorComponent},
  {path: 'fi/generator/.', component: GeneratorComponent},
  {path: 'fr/generator/.', component: GeneratorComponent},
  {path: 'de/generator/.', component: GeneratorComponent},
  {path: 'el/generator/.', component: GeneratorComponent},
  {path: 'hi/generator/.', component: GeneratorComponent},
  {path: 'hu/generator/.', component: GeneratorComponent},
  {path: 'id/generator/.', component: GeneratorComponent},
  {path: 'it/generator/.', component: GeneratorComponent},
  {path: 'ja/generator/.', component: GeneratorComponent},
  {path: 'ko/generator/.', component: GeneratorComponent},
  {path: 'zh/generator/.', component: GeneratorComponent},
  {path: 'mr/generator/.', component: GeneratorComponent},
  {path: 'no/generator/.', component: GeneratorComponent},
  {path: 'pl/generator/.', component: GeneratorComponent},
  {path: 'pt/generator/.', component: GeneratorComponent},
  {path: 'pa/generator/.', component: GeneratorComponent},
  {path: 'ro/generator/.', component: GeneratorComponent},
  {path: 'ru/generator/.', component: GeneratorComponent},
  {path: 'sk/generator/.', component: GeneratorComponent},
  {path: 'es/generator/.', component: GeneratorComponent},
  {path: 'sv/generator/.', component: GeneratorComponent},
  {path: 'ta/generator/.', component: GeneratorComponent},
  {path: 'te/generator/.', component: GeneratorComponent},
  {path: 'th/generator/.', component: GeneratorComponent},
  {path: 'tr/generator/.', component: GeneratorComponent},
  {path: 'ur/generator/.', component: GeneratorComponent},
  {path: 'vi/generator/.', component: GeneratorComponent},
  {path: 'sale/', component: SaleComponent},
  {path: 'ar/sale/', component: SaleComponent},
  {path: 'bn/sale/', component: SaleComponent},
  {path: 'hr/sale/', component: SaleComponent},
  {path: 'cs/sale/', component: SaleComponent},
  {path: 'nl/sale/', component: SaleComponent},
  {path: 'fi/sale/', component: SaleComponent},
  {path: 'fr/sale/', component: SaleComponent},
  {path: 'de/sale/', component: SaleComponent},
  {path: 'el/sale/', component: SaleComponent},
  {path: 'hi/sale/', component: SaleComponent},
  {path: 'hu/sale/', component: SaleComponent},
  {path: 'id/sale/', component: SaleComponent},
  {path: 'it/sale/', component: SaleComponent},
  {path: 'ja/sale/', component: SaleComponent},
  {path: 'ko/sale/', component: SaleComponent},
  {path: 'zh/sale/', component: SaleComponent},
  {path: 'mr/sale/', component: SaleComponent},
  {path: 'no/sale/', component: SaleComponent},
  {path: 'pl/sale/', component: SaleComponent},
  {path: 'pt/sale/', component: SaleComponent},
  {path: 'pa/sale/', component: SaleComponent},
  {path: 'ro/sale/', component: SaleComponent},
  {path: 'ru/sale/', component: SaleComponent},
  {path: 'sk/sale/', component: SaleComponent},
  {path: 'es/sale/', component: SaleComponent},
  {path: 'sv/sale/', component: SaleComponent},
  {path: 'ta/sale/', component: SaleComponent},
  {path: 'te/sale/', component: SaleComponent},
  {path: 'th/sale/', component: SaleComponent},
  {path: 'tr/sale/', component: SaleComponent},
  {path: 'ur/sale/', component: SaleComponent},
  {path: 'vi/sale/', component: SaleComponent},
  {path: ':keyword', component: IndexComponent},
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
